# -*- fill-column: 80; org-confirm-babel-evaluate: nil -*-

#+TITLE:     Assignment 14, Linear Algebra 1
#+AUTHOR:    Oleg Sivokon
#+EMAIL:     olegsivokon@gmail.com
#+DATE:      <2015-01-10 Sat>
#+Description: Fourth asssignment in the course Linear Algebra 1
#+KEYWORDS: Assignment, Linear Algebra
#+LANGUAGE: en
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [fleqn]
#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{color}
#+LATEX_HEADER: \usepackage{a4wide}
#+LATEX_HEADER: \usepackage[backend=bibtex, style=numeric]{biblatex}
#+LATEX_HEADER: \usepackage{commath}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usetikzlibrary{shapes,backgrounds}
#+LATEX_HEADER: \usepackage{marginnote}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \hypersetup{urlcolor=blue}
#+LATEX_HEADER: \hypersetup{colorlinks,urlcolor=blue}
#+LATEX_HEADER: \addbibresource{bibliography.bib}
#+LATEX_HEADER: \setlength{\parskip}{16pt plus 2pt minus 2pt}
#+LATEX_HEADER: \definecolor{codebg}{rgb}{0.96,0.99,0.8}
#+LATEX_HEADER: \DeclareMathOperator{\Sp}{Sp}
#+LATEX_HEADER: \DeclareMathOperator{\Solutions}{P}
#+LATEX_HEADER: \DeclareMathOperator{\Dim}{Dim}

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./css/style.css"/>
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="./css/bootstrap.min.css"/>
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="./css/icfp.css"/>

#+BEGIN_SRC emacs-lisp :exports none
(setq org-latex-pdf-process
        '("latexmk -pdflatex='pdflatex -shell-escape -interaction nonstopmode' -pdf -bibtex -f %f")
        org-latex-listings t
        org-src-fontify-natively t
        org-babel-latex-htlatex "htlatex")
(defmacro by-backend (&rest body)
    `(cl-case (when (boundp 'backend) (org-export-backend-name backend))
       ,@body))
#+END_SRC

#+RESULTS:
: by-backend

#+BEGIN_LATEX
  \lstset{ %
    backgroundcolor=\color{codebg},
    basicstyle=\ttfamily\scriptsize,
    breakatwhitespace=false,         % sets if automatic breaks should only happen at whitespace
    breaklines=false,
    captionpos=b,                    % sets the caption-position to bottom
    commentstyle=\color{mygreen},    % comment style
    framexleftmargin=10pt,
    xleftmargin=10pt,
    framerule=0pt,
    frame=tb,                        % adds a frame around the code
    keepspaces=true,                 % keeps spaces in text, useful for keeping indentation of code (possibly needs columns=flexible)
    keywordstyle=\color{blue},       % keyword style
    showspaces=false,                % show spaces everywhere adding particular underscores; it overrides 'showstringspaces'
    showstringspaces=false,          % underline spaces within strings only
    showtabs=false,                  % show tabs within strings adding particular underscores
    stringstyle=\color{codestr},     % string literal style
    tabsize=2,                       % sets default tabsize to 2 spaces
  }
#+END_LATEX

@@latex: \clearpage@@

* Problems

** Problem 1

   Let $W$ and $U$ be subspaces of $\mathbb{R}^4[x]$:
   #+HEADER: :exports results
   #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
   #+BEGIN_SRC latex
     \begin{align*}
       U &= \Sp \{ x^3 + 4x^2 - x + 3, x^3 + 5x^2 + 5, 3x^3 + 10x^2 + 5 \} \\
       W &= \Sp \{ x^3 + 4x^2 + 6, x^3 + 2x^2 - x + 5, 2x^3 + 2x^2 - 3x + 9 \}
     \end{align*}
   #+END_SRC
 
   1. Find dimension, basis of $U$, $W$ and $U+W$.
   2. What is the dimension and basis of $U \cap W$?
   3. Find a subspace $T$ such that $T \oplus W = \mathbb{R}^4[x]$.
        
*** Answer 1
    In order to find dimension, I can first find the basis, and then simply
    count the number of vectors in it.  Since basis by definition has to be
    linearly independent, I will adjoin vectors of $U$ to a matrix, will do
    the same for vectors of $W$, triangularize these matrices and remove the
    zero rows to obtain the basis.

    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{multline*}
        \begin{bmatrix}
          1 & 2  & -1 & 3 \\
          1 & 5  & 0  & 5 \\
          3 & 10 & 0  & 5 \\
        \end{bmatrix}
        \xrightarrow{R_1 = R_2, R_2 = R_1}
        \begin{bmatrix}
          1 & 5  & 0  & 5 \\
          1 & 2  & -1 & 3 \\
          3 & 10 & 0  & 5 \\
        \end{bmatrix}
        \xrightarrow{R_3 = R_3 - 3R_1}
        \begin{bmatrix}
          1 & 5  & 0  & 5 \\
          1 & 2  & -1 & 3 \\
          0 & -5 & 0  & -10 \\
        \end{bmatrix} \\ \\
        \xrightarrow{R_2 = R_3, R_3 = R_2}
        \begin{bmatrix}
          1 & 5  & 0  & 5 \\
          0 & -5 & 0  & -10 \\
          1 & 2  & -1 & 3 \\
        \end{bmatrix}
        \xrightarrow{R_3 = R_3 - R_1}
        \begin{bmatrix}
          1 & 5  & 0  & 5 \\
          0 & -5 & 0  & -10 \\
          0 & -7  & -1 & -2 \\
        \end{bmatrix}
        \xrightarrow{R_3 = R_3 - R_2} \\ \\
        \begin{bmatrix}
          1 & 5  & 0  & 5 \\
          0 & -5 & 0  & -10 \\
          0 & -2 & -1 & 8 \\
        \end{bmatrix}
        \xrightarrow{R_3 = 5R_3}
        \begin{bmatrix}
          1 & 5   & 0  & 5 \\
          0 & -5  & 0  & -10 \\
          0 & -10 & -5 & 40 \\
        \end{bmatrix}
        \xrightarrow{R_3 = R_3 - 2R_2}
        \begin{bmatrix}
          1 & 5  & 0  & 5 \\
          0 & -5 & 0  & -10 \\
          0 & 0  & -5 & 20 \\
        \end{bmatrix}
      \end{multline*}
    #+END_SRC


    Hence the basis of $U$ is $\{x^3+5x^2+5, -5x^2-10, -5x+20\}$. And its dimension is 3.

    Similarly, for $W$:

    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{multline*}
        \begin{bmatrix}
          1 & 4 & 0  & 6 \\
          1 & 2 & -1 & 5 \\
          2 & 2 & -3 & 9 \\
        \end{bmatrix}
        \xrightarrow{R_1 = R_2, R_2 = R_1}
        \begin{bmatrix}
          1 & 4  &  0 & 6 \\
          0 & -2 & -1 & -1 \\
          0 & 6  & -3 & -3 \\
        \end{bmatrix}
        \xrightarrow{R_3 = R_3 - 3R_1}
        \begin{bmatrix}
          1 & 4  &  0 & 6 \\
          0 & -2 & -1 & -1 \\
          0 & 0  & 0 & 0 \\
        \end{bmatrix}
      \end{multline*}
    #+END_SRC




    Hence the basis of $W$ is $\{x^3+4x^2+6, -2x^2-x-1\}$, and its dimension is 2.

    Now, let's find the basis of $V+U$.  Again, adjoin the bases of $U$ and $W$,
    triangularize and remove all zero vectors if any.


    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{multline*}
        \begin{bmatrix}
          1 &  5 &  0 &  5 \\
          0 & -5 &  0 & -10 \\
          0 &  0 & -5 &  20 \\
          1 &  4 &  0 &  6 \\
          0 & -2 & -1 & -1 \\
        \end{bmatrix}
        \xrightarrow{R_1 = R_2, R_2 = R_1}
        \begin{bmatrix}
          1 &  5 &  0 &  5 \\
          0 & -5 &  0 & -10 \\
          0 &  0 & -5 &  20 \\
          0 & -1 &  0 & -1 \\
          0 & -2 & -1 & -1 \\
        \end{bmatrix}
        \xrightarrow{R_3 = R_3 - 3R_1}
        \begin{bmatrix}
          1 &  5 &  0 &  5 \\
          0 & -5 &  0 & -10 \\
          0 &  0 & -5 &  20 \\
          0 & -1 &  0 & -1 \\
          0 &  0 & -1 &  1 \\
        \end{bmatrix} \\ \\
        \xrightarrow{R_3 = R_3 - 3R_1}
        \begin{bmatrix}
          1 &  5 &  0 &  5 \\
          0 & -1 &  0 & -1 \\
          0 &  0 & -5 &  20 \\
          0 & -5 &  0 & -10 \\
          0 &  0 & -1 &  1 \\
        \end{bmatrix}
        \xrightarrow{R_3 = R_3 - 3R_1}
        \begin{bmatrix}
          1 &  5 &  0 &  5 \\
          0 & -1 &  0 & -1 \\
          0 &  0 & -5 &  20 \\
          0 &  0 &  0 & -5 \\
          0 &  0 & -1 &  1 \\
        \end{bmatrix}
        \xrightarrow{R_3 = R_3 - 3R_1} \\ \\
        \begin{bmatrix}
          1 &  5 &  0 &  5 \\
          0 & -1 &  0 & -1 \\
          0 &  0 & -1 &  1 \\
          0 &  0 &  0 & -5 \\
          0 &  0 & -5 &  20 \\
        \end{bmatrix}
        \xrightarrow{R_3 = R_3 - 3R_1}
        \begin{bmatrix}
          1 &  5 &  0 &  5 \\
          0 & -1 &  0 & -1 \\
          0 &  0 & -1 &  1 \\
          0 &  0 &  0 & -5 \\
          0 &  0 &  0 &  15 \\
        \end{bmatrix}
        \xrightarrow{R_3 = R_3 - 3R_1}
        \begin{bmatrix}
          1 &  5 &  0 &  5 \\
          0 & -1 &  0 & -1 \\
          0 &  0 & -1 &  1 \\
          0 &  0 &  0 & -5 \\
          0 &  0 &  0 &  0 \\
        \end{bmatrix}
      \end{multline*}
    #+END_SRC

    Since $\Dim(V)=4$ and $\Dim(U)+\Dim(W)=5$ it follows that $\Dim(U\cap W)$ has
    to be 1.  This follows from the formula of sum of dimensions of subspaces, which
    says $\Dim(V)=\Dim(S)+\Dim(T)-\Dim(S\cap T)$.

** Problem 2
   
   Let $U$ and $W$ be subspaces of $\mathbb{R}^4$ such that $\Dim(U)>\Dim(W)$.
   Provided that $W \cap U = \Sp \{(1, 2, 3, 4), (1, 1, 1, 1), (-1, 0, 1, 2)\}$,
   and $(0, 0, 1, 0) \not \in U + W$.  Find the dimension of $U+W$ and its basis.

** Problem 3

   Given the following subspaces of $\mathbb{R}^4$:
   #+HEADER: :exports results
   #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
   #+BEGIN_SRC latex
     \begin{align*}
       U &= \Sp \{ (a, a-1, a, 4), (2, 2, 1, -3) \} \\
       W &= \Solutions\Big(\left.
         \begin{alignedat}{5}
           & x + & y +  & z  &{}={}& 0 \\
           & y + & 2z - & 2t &{}={}& 0 \\
         \end{alignedat}
       \right\}\Big)
     \end{align*}
   #+END_SRC
   Where $\Solutions(X)$ is the vector space of all solutions of linear system $X$.

   Find values of $a$ for which holds that $\Dim(U \cap W)=1$. Show the basis of
   $U \cap W$ in this case.

** Problem 4

   Prove or disprove each of the following statements:

   1. If $B=\{\vec{v_1}, \ldots, \vec{v_n}\}$ is the basis of $V$ and $U \subseteq V$ is
      a subspace of dimension $k$, $k \leq n$, then there are $k$ vectors in $B$ spanning
      $U$.
   2. If $V$ is a vectors pace of dimension $n$ and if $m \leq n, m \in \mathbb{N}$, then
      exists sub-space $U$ of $V$ with dimension equal to $m$.

** Problem 5

   In field $\mathbb{F}$ are given members $a_1, a_2, \ldots, a_m$, not all zero and,
   similarly, $b_1, b_2, \ldots, b_n$ not all zero.  What is the dimension of the
   matrix given by:
   #+HEADER: :exports results
   #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
   #+BEGIN_SRC latex
     \begin{align*}
       M     &= (m_{ij})_{1<i<m, 1<j<n} \\
       m_{ij} &= a_ib_j
     \end{align*}
   #+END_SRC

** Problem 6

   Let $V$ be a vector space over $\mathbb{R}$ of dimension 3, and let $B$ be its basis.
   Given vectors $\vec{v_1}, \vec{v_2}, \vec{v_3}$ and $\vec{w}$ in $V$:
   #+HEADER: :exports results
   #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
   #+BEGIN_SRC latex
     \begin{equation*}
       [v_1]_B= \begin{pmatrix}  2 \\  3 \\  5 \\ \end{pmatrix},
       [v_2]_B= \begin{pmatrix}  1 \\ -2 \\ -3 \\ \end{pmatrix},
       [v_3]_B= \begin{pmatrix} -3 \\  2 \\ -1 \\ \end{pmatrix},
       [w]_B=   \begin{pmatrix}  5 \\  5 \\ 16 \\ \end{pmatrix}
     \end{equation*}
   #+END_SRC
   Prove that $C=(\vec{v_1}, \vec{v_2}, \vec{v_3})$ is the basis of $V$ and find $[w]_C$.
