# -*- fill-column: 80; org-confirm-babel-evaluate: nil -*-

#+TITLE:     Assignment 13, Linear Algebra 1
#+AUTHOR:    Oleg Sivokon
#+EMAIL:     olegsivokon@gmail.com
#+DATE:      <2016-04-16 Sat>
#+DESCRIPTION: Third asssignment in the course Linear Algebra 1
#+KEYWORDS: Assignment, Linear Algebra
#+LANGUAGE: en
#+LaTeX_CLASS: article
#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{color}
#+LATEX_HEADER: \usepackage{a4wide}
#+LATEX_HEADER: \usepackage{commath}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{marginnote}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \hypersetup{urlcolor=blue}
#+LATEX_HEADER: \hypersetup{colorlinks,urlcolor=blue}
#+LATEX_HEADER: \setlength{\parskip}{16pt plus 2pt minus 2pt}
#+LATEX_HEADER: \definecolor{codebg}{rgb}{0.96,0.99,0.8}
#+LATEX_HEADER: \DeclareMathOperator{\Sp}{Sp}

#+BEGIN_SRC emacs-lisp :exports none
  (setq org-latex-pdf-process
          '("latexmk -pdflatex='pdflatex -shell-escape -interaction nonstopmode' -pdf -f %f")
          ;; org-latex-listings t
          org-src-fontify-natively t
          ;; org-latex-custom-lang-environments '((maxima "maxima"))
          ;; org-listings-escape-inside '("(*@" . "@*)")
          ;; org-babel-latex-htlatex "htlatex"
          )

    (defmacro by-backend (&rest body)
      `(progn
         (cl-case org-export-current-backend ,@body)))
#+END_SRC

#+RESULTS:
: by-backend

#+BEGIN_LATEX
\definecolor{codebg}{rgb}{0.96,0.99,0.8}
\lstnewenvironment{maxima}{%
  \lstset{backgroundcolor=\color{codebg},
    frame=single,
    framerule=0pt,
    basicstyle=\ttfamily\scriptsize,
    columns=fixed}}{}
}
\makeatletter
\newcommand{\verbatimfont}[1]{\renewcommand{\verbatim@font}{\ttfamily#1}}
\makeatother
\verbatimfont{\small}%
\makeatletter
\renewcommand*\env@matrix[1][*\c@MaxMatrixCols c]{%
  \hskip -\arraycolsep
  \let\@ifnextchar\new@ifnextchar
  \array{#1}}
\makeatother
\clearpage
#+END_LATEX

* Problems

** Problem 1
   1. Find all solutions of $z^3 + 3i\overline{z} = 0$.
   2. Let $z_1, z_2$ be complex numbers.  Prove that unless $z_1z_2 = 1$ and
      $\abs{z_1} = \abs{z_2} = 1$, then $\frac{z_1 + z_2}{1 + z_1z_2}$ is a real
      number.

** Problem 2
   Let $\mathbb{Q}$ denote the field of rational numbers.  And $K$ defined as follows:
   #+HEADER: :exports results
   #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
   #+BEGIN_SRC latex
     \begin{align*}
     K = \left\{\begin{bmatrix}
           a & 2b \\
           b & a
         \end{bmatrix} \;|\; a,b \in \mathbb{Q}\right\}\;.
     \end{align*}
   #+END_SRC

   Is $K$ a field under matrix addition and multiplication?

** Problem 3
   Verify that $V$ is a vectors space over field $\textbf{F}$:
   1. $\textbf{F} = \mathbb{C}, V = \mathbb{M}_{n\times n}^{\mathbb{C}}$ and
      addition defined to be the rational addition, while multiplication is
      defined to be $\lambda\times A = \abs{\lambda}\times A$.
   2. $\textbf{F} = \mathbb{R}, V = \{(x,y) \in \mathbb{R}^2\;|\;y=2x\}$,
      with addition being the addition of $\mathbb{R}^2$ and multiplication
      $\lambda\times (x,y) = (\lambda x, 0)$.

** Problem 4
   Given sets:
   1. $K = \{(x,y,z,t) \in \mathbb{R}^4\;|\; x+y-z+t=0 \land 2x+y+z-3t=0\}$.
   2. $L = \{f \in V\;|\; f\left(\frac{1}{2}\right)>f(2)\}$, $V$ is the vector
      space of all real-valued functions.
   3. $M = \{p(x) \in \mathbb{R}^4[x]\;|\; p(-3) = 0\}$.
   4. $R = \{(x,y) \in \mathbb{R}^3\;|\; x^2 + y^2 = 0\}$.
   5. $R = \{(x,y) \in \mathbb{R}^3\;|\; x^2 - y^2 = 0\}$.
      
   Fore each of sets given, assert them being vector spaces.  In case they are,
   prove this in two different ways.

** Problem 5
   Given vector space $V$ and $\vec{v}_1, \vec{v}_2, \vec{v}_3$ distinct vectors
   prove or disprove:
   1. If $\Sp\{\vec{v}_1, \vec{v}_2\} = \Sp\{\vec{v}_1, \vec{v}_3\}$, then
      $\vec{v}_2$ is a multiple of $\vec{v}_3$.
   2. If $\vec{v}_1 - 2\vec{v}_2 + \vec{v}_3 = \vec{0}$, then 
      $\Sp\{\vec{v}_1, \vec{v}_2\} = \Sp\{\vec{v}_1, \vec{v}_3\}$.
   3. If $\{\vec{v}_1, \vec{v}_2, \vec{v}_3\}$ is linearly dependent, then
      $\Sp\{\vec{v}_1, \vec{v}_2\} = \Sp\{\vec{v}_1 + \vec{v}_3, \vec{v}_3 +
      \vec{v}_3\}$.

** Problem 6
   Given following subspaces of $\mathbb{R}^4$:
   $U = \Sp\{(1,1,2), (2,2,1)\}$ and $W = \Sp\{(1,3,4), (2,5,1)\}$,
   find spanning set of $U \cap W$.
