# -*- fill-column: 80; org-confirm-babel-evaluate: nil -*-

#+TITLE:     Assignment 12, Linear Algebra 1
#+AUTHOR:    Oleg Sivokon
#+EMAIL:     olegsivokon@gmail.com
#+DATE:      <2016-03-26 Sat>
#+DESCRIPTION: Second asssignment in the course Linear Algebra 1
#+KEYWORDS: Assignment, Linear Algebra
#+LANGUAGE: en
#+LaTeX_CLASS: article
#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{color}
#+LATEX_HEADER: \usepackage{a4wide}
#+LATEX_HEADER: \usepackage{commath}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{marginnote}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \hypersetup{urlcolor=blue}
#+LATEX_HEADER: \hypersetup{colorlinks,urlcolor=blue}
#+LATEX_HEADER: \setlength{\parskip}{16pt plus 2pt minus 2pt}
#+LATEX_HEADER: \definecolor{codebg}{rgb}{0.96,0.99,0.8}

#+BEGIN_SRC emacs-lisp :exports none
  (setq org-latex-pdf-process
          '("latexmk -pdflatex='pdflatex -shell-escape -interaction nonstopmode' -pdf -f %f")
          ;; org-latex-listings t
          org-src-fontify-natively t
          ;; org-latex-custom-lang-environments '((maxima "maxima"))
          ;; org-listings-escape-inside '("(*@" . "@*)")
          ;; org-babel-latex-htlatex "htlatex"
          )

    (defmacro by-backend (&rest body)
      `(progn
         (cl-case org-export-current-backend ,@body)))
#+END_SRC

#+RESULTS:
: by-backend

#+BEGIN_LATEX
\definecolor{codebg}{rgb}{0.96,0.99,0.8}
\lstnewenvironment{maxima}{%
  \lstset{backgroundcolor=\color{codebg},
    frame=single,
    framerule=0pt,
    basicstyle=\ttfamily\scriptsize,
    columns=fixed}}{}
}
\makeatletter
\newcommand{\verbatimfont}[1]{\renewcommand{\verbatim@font}{\ttfamily#1}}
\makeatother
\verbatimfont{\small}%
\makeatletter
\renewcommand*\env@matrix[1][*\c@MaxMatrixCols c]{%
  \hskip -\arraycolsep
  \let\@ifnextchar\new@ifnextchar
  \array{#1}}
\makeatother
\clearpage
#+END_LATEX

* Problems

** Problem 1
   Let $A$ be a square matrix of order $3 \times 3$ s.t. $A^3 = 0$, but
   $A^2 \neq 0$.

   1. Prove that there exists a vector $\vec{v} \in \mathbb{R}^3$ s.t. $A\vec{v}
      \neq 0$.
   2. Prove that there exits vectors $\vec{v} \in \mathbb{R}^3$ s.t.
      $\{\vec{v}, \vec{v}A, \vec{v}A^2\}$ are the basis of $\mathbb{R}^3$.

*** Answer 1
    Notice that $A$ itself is made of the column vectors, call them $r_1, r_2,
    r_3$.  All of which are in $\mathbb{R}^3$.  Suppose, for contradiction, that
    there is no vector in $\vec{v} \in \mathbb{R}^3$ satisfying $A\vec{v} \neq
    0$.  In particular, none of the $\vec{r}_1, \vec{r}_2, \vec{r}_3$ satisfies
    the above condition.  In other words, $A\vec{r}_1 = 0$, $A\vec{r}_2 = 0$,
    $A\vec{r}_3 = 0$.  (where 0 means zero matrix).  On the other hand,
    $A\vec{r}_1 + A\vec{r}_2 + A\vec{r}_3 = A^2 \neq 0$.  Contradiction.  Hence,
    there exists $\vec{v} \in \mathbb{R}^3$ s.t. $A\vec{v} \neq 0$.

*** Answer 2
    
** Problem 2
   Given square matrices $A, B, C, D$ of order $n \times n$ s.t. $ABCD = I$,
   prove that $ABCD = DABC = CDAB = BCDA = I$.

*** Answer 3
    The proof is immediate from the definition of inverse: $XX^{-1} = I$ and
    associativity of matrix multiplication.  In other words:
    
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{align*}
        ABCD &= I \iff \\
        A(BCD) &= I \iff \\
        A^{-1} &= BCD \iff \\
        DABC &= I \iff \\
        AB(CD) &= I \iff \\
        (AB)^{-1} &= CD \iff \\
        CDAB &= I \iff \\
        A^{-1}A &= I \iff \\
        I &= BCDA \;.
      \end{align*}
    #+END_SRC

** Problem 3
   Let $A$ be a square matrix of order $m \times m$, let $B$ be a matrix of
   order $m \times n$.  Prove in two different ways that if $A$ is invertible,
   then $B\vec{x} = 0$ and $AB\vec{x} = 0$ has the same solution space.

*** Answer 4

** Problem 4
   Given matrix $A$ of a general form:

   #+HEADER: :exports results
   #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
   #+BEGIN_SRC latex
     \begin{align*}
       \begin{bmatrix}
         0      & a_1    & \dots  & 0      & 0 \\
         0      & 0      & a_2    & \dots  & 0 \\
         \vdots & \vdots & \vdots & \ddots & \vdots \\
         0      & 0      & 0      & \dots  & a_{n-1} \\
         a_n    & 0      & 0      & \dots  & 0
       \end{bmatrix}
     \end{align*}
   #+END_SRC

   Prove that it is invertible, show $A^{-1}$.

*** Answer 5
    Performing elementary operations: $R_n \to R_1$ and $R_k \to R_{k+1}, 1 \leq
    k < n$ gives us diagonal matrix.  This matrix is invertible since it has a
    pivot element in each of its columns.

    The inverse of $A$ will, in general look like this:

    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{align*}
        \begin{bmatrix}
          0             & 0             & \dots  & 0                & \frac{1}{a_n} \\
          \frac{1}{a_1} & 0             & \dots  & 0                & 0 \\
          0             & \frac{1}{a_2} & \dots  & 0                & 0 \\
          \vdots        & \vdots        & \ddots & \vdots           & \vdots \\
          0             & 0             & \dots  & \frac{1}{a_{n-1}} & 0 \\
        \end{bmatrix}
      \end{align*}
    #+END_SRC

    Notice that for each row of $A$, we will be matching the column of $A^{-1}$.
    We need to make sure that the only non-zero element of $A_c$ was matched by
    the only non-zero element of $A^{-1}_r$ (where $c$ stands for column index
    and $r$ stands for row index).  In order to obtain a diagonal with all ones
    (i.e. the identity matrix), we need to also make sure that $A_{c,i} \times
    A^{-1}_{r,j} = 1$.  In other words, we need to match $a_1$ with $\frac{1}{a_1}$,
    $a_2$ with $\frac{1}{a_2}$, and so on.

** Problem 5
   Let $A$ and $B$ be square matrices of the order $3 \times 3$ s.t. $B^2A = -2B^3$
   and $B^3 + AB^2 = 3I$.

   Prove that $A$ and $B$ are invertible and express $A^{-1}$ and $B^{-1}$ in
   terms of $B$.

*** Answer 6
    Using some matrix algebra we obtain: $B^{-1} = -\frac{1}{3}B^2$ and $A^{-1}
    = (-2B)^{-1}$.

    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{align*}
        B^2A &= -2B^3 \iff \\
        B^2A &= B^2(-2I)B \iff \\
        A &= -2B \\
        &\textit{substituting into second equation:} \\
        B^3 + AB^2 &= 3I \iff \\
        B^3 - 2B^3 &= 3I \iff \\
        -B^3 &= 3I \iff \\
        B(-B^2) &= 3I \iff \\
        B(-\frac{1}{3}B^2) &= I \iff \\
        B^{-1} &= -\frac{1}{3}B^2 \\
        &\textit{$A$ is invertible because it is similar to $B$} \\
        -2B &= (\sqrt{2}I)B(\sqrt{2}I^{-1}) \\
        A^{-1} &= (-2B)^{-1} \;.
      \end{align*}
    #+END_SRC
